const data = {
    "Basics of Programming ": {
        "Getting Started": {
            "How To Print In Java": "https://www.pepcoding.com/resources/online-java-foundation/getting-started/how-to-print-in-java-article-official/topic",
            "Print Z Easy": "https://www.pepcoding.com/resources/online-java-foundation/getting-started/print-z-official/ojquestion",
            "Grading System Easy": "https://www.pepcoding.com/resources/online-java-foundation/getting-started/grading-system-official/ojquestion",
            "Is A Number Prime Easy": "https://www.pepcoding.com/resources/online-java-foundation/getting-started/is-number-prime-official/ojquestion",
            "Print All Primes Till N Easy": "https://www.pepcoding.com/resources/online-java-foundation/getting-started/print-all-primes-till-n-official/ojquestion",
            "Print Fibonacci Numbers Till N Easy": "https://www.pepcoding.com/resources/online-java-foundation/getting-started/fibonacci-till-n-official/ojquestion",
            "Count Digits In A Number Easy": "https://www.pepcoding.com/resources/online-java-foundation/getting-started/count-digits-official/ojquestion",
            "Digits Of A Number Easy": "https://www.pepcoding.com/resources/online-java-foundation/getting-started/digits-of-a-number-official/ojquestion",
            "Reverse A Number Easy": "https://www.pepcoding.com/resources/online-java-foundation/getting-started/rotate-a-number-official/ojquestion",
            "Inverse Of A Number Easy": "https://www.pepcoding.com/resources/online-java-foundation/getting-started/inverse-of-a-number-official/ojquestion",
            "Rotate A Number Easy": "https://www.pepcoding.com/resources/online-java-foundation/getting-started/rotate-a-number-official/ojquestion",
            "Gcd And Lcm Easy": "https://www.pepcoding.com/resources/online-java-foundation/getting-started/gcd-and-lcm-official/ojquestion",
            "Prime Factorisation Of A Number Easy": "https://www.pepcoding.com/resources/online-java-foundation/getting-started/prime-factorisation-official/ojquestion",
            "Pythagorean Triplet Easy": "https://www.pepcoding.com/resources/online-java-foundation/getting-started/pythagorean-triplet-official/ojquestion",
            "The Curious Case Of Benjamin Bulbs Easy": "https://www.pepcoding.com/resources/online-java-foundation/getting-started/benjamin-bulbs-official/ojquestion",
        },
        "Patterns": {
            "Pattern 1 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/pattern-type-1-official/ojquestion",
            "Pattern 2 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/pattern-type-2-official/ojquestion",
            "Pattern 3 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/pattern-type-3-official/ojquestion",
            "Pattern 4 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/pattern-type-4-official/ojquestion",
            "Pattern 5 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/pattern-type-5-official/ojquestion",
            "Pattern 6 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/design-pattern-6-official/ojquestion",
            "Pattern 7 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/design-pattern-7-official/ojquestion",
            "Pattern 8 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/design-pattern-8-official/ojquestion",
            "Pattern 9 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/design-pattern-9-official/ojquestion",
            "Pattern 10 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/design-pattern-10-official/ojquestion",
            "Pattern 11 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/design-pattern-11-official/ojquestion",
            "Pattern 12 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/design-pattern-12-official/ojquestion",
            "Pattern 13 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/design-pattern-13-official/ojquestion",
            "Pattern 14 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/design-pattern-14-official/ojquestion",
            "Pattern 15 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/design-pattern-15-official/ojquestion",
            "Pattern 16 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/design-pattern-16-official/ojquestion",
            "Pattern 17 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/design-pattern-17-official/ojquestion",
            "Pattern 18 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/design-pattern-18-official/ojquestion",
            "Pattern 19 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/design-pattern-19-official/ojquestion",
            "Pattern 20 Easy": "https://www.pepcoding.com/resources/online-java-foundation/patterns/design-pattern-20-official/ojquestion",
        },
        "Function and Arrays": {
            "Decimal To Any Base Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/decimal-to-any-base-official/ojquestion",
            "Any Base To Decimal Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/any-base-to-decimal-official/ojquestion",
            "Any Base To Any Base Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/any-base-to-any-base-official/ojquestion",
            "Any Base Addition Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/any-base-addition-official/ojquestion",
            "Any Base Subtraction Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/any-base-subtraction-official/ojquestion",
            "Any Base Multiplication Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/any-base-multiplication-official/ojquestion",
            "Span Of Array Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/span-of-array-official/ojquestion",
            "Find Element In An Array Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/find-element-in-array-official/ojquestion",
            "Bar Chart Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/bar-chart-official/ojquestion",
            "Sum Of Two Arrays Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/sum-of-two-arrays-official/ojquestion",
            "Difference Of Two Arrays Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/difference-of-two-arrays-official/ojquestion",
            "Reverse An Array Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/reverse-an-array-official/ojquestion",
            "Rotate An Array Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/rotate-an-array-official/ojquestion",
            "Inverse Of An Array Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/inverse-of-an-array-official/ojquestion",
            "Subarray Problem Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/subarray-problem-official/ojquestion",
            "Subsets Of Array Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/subsets-of-array-official/ojquestion",
            "Broken Economy Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/ceil-floor-official/ojquestion",
            "First Index And Last Index Easy": "https://www.pepcoding.com/resources/online-java-foundation/function-and-arrays/first-index-last-index-official/ojquestion",
        },
        "2D Arrays": {
            "2d Arrays Demo Easy": "https://www.pepcoding.com/resources/online-java-foundation/2d-arrays/2d-arrays-demo-official/ojquestion",
            "Matrix Multiplication Easy": "https://www.pepcoding.com/resources/online-java-foundation/2d-arrays/matrix-multiplication-official/ojquestion",
            "The State Of Wakanda - 1 Easy": "https://www.pepcoding.com/resources/online-java-foundation/2d-arrays/wakanda-1-official/ojquestion",
            "Spiral Display Easy": "https://www.pepcoding.com/resources/online-java-foundation/2d-arrays/spiral-display-official/ojquestion",
            "Exit Point Of A Matrix Easy": "https://www.pepcoding.com/resources/online-java-foundation/2d-arrays/exit-point-matrix-official/ojquestion",
            "Rotate By 90 Degree Easy": "https://www.pepcoding.com/resources/online-java-foundation/2d-arrays/rotate-by-90-degree-official/ojquestion",
            "Ring Rotate Easy": "https://www.pepcoding.com/resources/online-java-foundation/2d-arrays/ring-rotate-official/ojquestion",
            "The State Of Wakanda - 2 Easy": "https://www.pepcoding.com/resources/online-java-foundation/2d-arrays/diagonal-traversal-official/ojquestion",
            "Saddle Price Easy": "https://www.pepcoding.com/resources/online-java-foundation/2d-arrays/saddle-price-official/ojquestion",
            "Search In A Sorted 2d Array Medium": "https://www.pepcoding.com/resources/online-java-foundation/2d-arrays/search-in-a-sorted-2d-array-official/ojquestion",
        },
        "String, String Builder and ArrayList": {
            "Print All Palindromic Substrings Easy": "https://www.pepcoding.com/resources/online-java-foundation/string,-string-builder-and-arraylist/print-all-palindromic-substrings-official/ojquestion",
            "String Compression Easy": "https://www.pepcoding.com/resources/online-java-foundation/string,-string-builder-and-arraylist/string-compression-official/ojquestion",
            "Toggle Case Easy": "https://www.pepcoding.com/resources/online-java-foundation/string,-string-builder-and-arraylist/toggle-case-official/ojquestion",
            "String With Difference Of Every Two Consecutive Characters Easy": "https://www.pepcoding.com/resources/online-java-foundation/string,-string-builder-and-arraylist/string-with-difference-of-every-two-consecutive-characters-official/ojquestion",
            " Print All Permutations Of A String Iteratively Easy": "https://www.pepcoding.com/resources/online-java-foundation/string,-string-builder-and-arraylist/print-all-permutations-of-a-string-iteratively-official/ojquestion",
            "Remove Primes Easy": "https://www.pepcoding.com/resources/online-java-foundation/string,-string-builder-and-arraylist/remove-primes-official/ojquestion"
        }
    },
    "Recursion and Backtracking ": {
        "Introduction to Recursion": {
            "Print Decreasing Easy": "https://www.pepcoding.com/resources/online-java-foundation/introduction-to-recursion/print-decreasing-official/ojquestion",
            "Print Increasing Easy": "https://www.pepcoding.com/resources/online-java-foundation/introduction-to-recursion/print-increasing-official/ojquestion",
            "Print Increasing Decreasing Easy": "https://www.pepcoding.com/resources/online-java-foundation/introduction-to-recursion/print-increasing-decreasing-official/ojquestion",
            "Factorial Easy": "https://www.pepcoding.com/resources/online-java-foundation/introduction-to-recursion/factorial-official/ojquestion",
            "Power-linear Easy": "https://www.pepcoding.com/resources/online-java-foundation/introduction-to-recursion/power-linear-official/ojquestion",
            "Power-logarithmic Easy": "https://www.pepcoding.com/resources/online-java-foundation/introduction-to-recursion/power-logarithmic-official/ojquestion",
            "Print Zigzag Easy": "https://www.pepcoding.com/resources/online-java-foundation/introduction-to-recursion/print-zig-zag-official/ojquestion",
            "Tower Of Hanoi Easy": "https://www.pepcoding.com/resources/online-java-foundation/introduction-to-recursion/toh-official/ojquestion"
        },
        "Recursion in Arrays": {
            "Display Array Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-in-arrays/display-array-official/ojquestion",
            "Display Array In Reverse Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-in-arrays/display-array-in-reverse/ojquestion",
            "Max Of An Array Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-in-arrays/max-of-an-array-official/ojquestion",
            "First Index Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-in-arrays/first-index-official/ojquestion",
            "Last Index Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-in-arrays/last-index-official/ojquestion",
            "All Indices Of Array Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-in-arrays/all-indices-official/ojquestion                    "
        },
        "Recursion with Arraylists": {
            "Get Subsequence Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-with-arraylists/get-subsequence-official/ojquestion",
            "Get Kpc Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-with-arraylists/get-kpc-official/ojquestion",
            "Get Stair Paths Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-with-arraylists/get-stair-paths-official/ojquestion",
            "Get Maze Paths Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-with-arraylists/get-maze-paths-official/ojquestion",
            "Get Maze Path With Jumps Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-with-arraylists/get-maze-path-with-jumps-official/ojquestion"
        },
        "Recursion on the way up": {
            "Print Subsequence Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-on-the-way-up/print-subsequence-official/ojquestion",
            "Print Kpc Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-on-the-way-up/print-kpc-official/ojquestion",
            "Print Stair Paths Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-on-the-way-up/print-stair-paths-official/ojquestion",
            "Print Maze Paths Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-on-the-way-up/print-maze-paths-official/ojquestion",
            "Print Maze Paths With Jumps Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-on-the-way-up/print-maze-path-with-jumps-official/ojquestion",
            "Print Permutations Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-on-the-way-up/print-permutations-official/ojquestion",
            "Print Encodings Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-on-the-way-up/print-encodings-official/ojquestion"
        },
        "Recursion Backtracking": {
            "Flood Fill Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-backtracking/flood-fill-official/ojquestion",
            "Target Sum Subsets Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-backtracking/target-sum-subsets-official/ojquestion",
            "N Queens Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-backtracking/n-queens-official/ojquestion",
            "Knights Tour Easy": "https://www.pepcoding.com/resources/online-java-foundation/recursion-backtracking/knights-tour-official/ojquestion"
        },
    }
}